apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamatodo
  namespace: tamakoapp
  labels:
    app: yamatodofront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yamatodofront
  template:
    metadata:
      labels:
        app: yamatodofront
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox
        command: ['sh', '-c', 'until nslookup tamako-db.criiqsqeswc6.ap-northeast-1.rds.amazonaws.com; do echo waiting for db; sleep 5; done;sleep 10'] # 後で修正検討
      containers:
        - name: front-app
          image: 296062576098.dkr.ecr.ap-northeast-1.amazonaws.com/tamako-ecr/main:front-prodv3 # 後で修正検討
          imagePullPolicy: Always 
          resources:
            limits:
              memory: "512Mi"  
              cpu: "500m"
          ports:
          - containerPort: 80


