apiVersion: v1
kind: Service
metadata:
  name: service-yamatodofront
  namespace: tamakoapp
spec:
  selector:
    app: yamatodofront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  namespace: tamakoapp
  name: back-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: yamatodo-back
  type: ClusterIP

---


apiVersion: v1
kind: Service
metadata:
  namespace: tamakoapp
  name: yama-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: yamatodo-db
  type: ExternalName
  externalName: tamako-db.criiqsqeswc6.ap-northeast-1.rds.amazonaws.com
